### ISSUE TITLE
Define Model Evaluation

### ISSUE THREAD

**Issue by RyanWri** [RyanWri/MaxSR#3]
Please review the paper again and understand what they evaluate and why? Metrics like PSNR/SSIM etc'

**Comment by DinKosberg** [comment]
**Data Pre Processing**
1. Convert Dataset From HR --> LR Using Bicubic interpolation.
   - Rotation - 90/180/270 deg
   - Flip Image
2. Model Evaluation
  - Performance Indicators - PSNR , SSIM
  - Explanation for each indicator.

**Comment by RyanWri** [comment]
@DinKosberg @MatanOz 
where is your pull request with the PSNR/SSIM and MAE evaluation?
please open a pr with relevant code.
